### ISSUE TITLE
Pre-publishing feedback

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-bean-validation#24]
**General**
- [ ] The Response Body that the guide asks the user to check for No Constraint Violations took a second to find, maybe it would help to move that response body further up so after you click execute it's the first thing the user sees/ make the response body more prominent because at the moment it seems as important as the curl line that you never draw the users attention to in the guide OR to explain the layout of the information presented in the application before asking the user to try it
- [ ] I found it difficult to find the Execute button because of how long the blue bar is

**What you'll learn**
- [x] Is the user expected to know CDI, JPA, JSF? If not, maybe some clarification/ full names would help if they are not expected to have that level of knowledge yet. 
- [x] The following sentence seems out of place, when did you mention setting rules on data? 
> To set rules on data, apply constraints by using annotations or XML configuration files.

**Try what you'll build**
- [x] The format of the "expand the /beanvalidation/validatespacecraft POST request to validate your spacecraft bean" section may not be consistent with other guides since we usually use that to reference commands/folders, especially since /beanvalidation/validatespacecraft/ looks like the start of a path. Perhaps this part could be bolded like the "Try it out" and the "Execute" since expanding that is similar to pressing a button.

**Applying constraints on the JavaBeans**
- [x] I noticed that the following sentence, perhaps this would be relevant in the intro section where you mention CDI in the first place
> To learn more about CDI, see Injecting dependencies into microservices. 

**Building & Running**
- [x] In try what you build, the instructions to replace the age/name values were done through copying and pasting but in this section, the instructions are to manually change the age/name values. This is a little inconsistent, maybe choose one way and stick to it (I think copying and pasting is much easier)

**Comment by evelinec** [comment]
The general issue are from OpenAPI. We can open issue there to have the address it. The "building and running" issue is not sever, as the "building and running" section have more detailed instruction for user to modify the fields to try out different results.

**Comment by evelinec** [comment]
- Can look into spelling out CDI, JPA, JSF
- To set rules on data, apply constraints by using annotations or XML configuration files. => this means, to set the constrain on the data field, the bean validation constrains are used. May not need rework. 
- The "try what you'll build" and "building and running" issues are the same, and explained above. 
- Can look into "To learn more about CDI, see Injecting dependencies into microservices." 

All these are minor.

**Comment by evelinec** [comment]
Looking into the place to report the OpenAPI issue. 

@justineechen can you review the assessment of the resolutions for the points you raised here. The following points will be addressed in issue #28: 

- Can look into spelling out CDI, JPA, JSF
- Can look into "To learn more about CDI, see Injecting dependencies into microservices."

**Comment by evelinec** [comment]
An issue is opened on the OpenAPI repo to address the UI improvements: https://github.com/eclipse/microprofile-open-api/issues/263
