### ISSUE TITLE
Inconsistent abstract?

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-bean-validation#29]
Abstract for the guide that you can find at https://openliberty.io/guides/bean-validation.html is different from what you see in the card for the guide at https://openliberty.io/guides/.

Also, "You’ll explore how to use bean validation in Open Liberty to create a microservice to validate user input data" is inconsistent in style with the other guides?  There is no "You'll"?

Moreover, "You’ll explore how to use bean validation in Open Liberty to create a microservice to validate user input data" appears to be somewhat at odds with "You will learn the basics of writing and testing a microservice that uses bean validation and the new functionality of Bean Validation 2.0. The service uses bean validation to validate that the supplied JavaBeans meet the defined constraints"?

A revision may be "Explore the use of bean validation to validate user input data for microservices".

**Comment by evelinec** [comment]
The abstract of the guide on the html page is to be updated by the following two attributes in the readme.adoc: 

```
:page-seo-title: 
:page-seo-description: 
```

**Comment by evelinec** [comment]
I believe the other issues are addressed for this issue.

**Comment by evelinec** [comment]
Fixed the SEO title and description for this guide. @yeekangc can we close this issue?

**Comment by yeekangc** [comment]
The abstract for the card and the one for the guide page have been fixed.  Then, the SEO title still needs work.  Closing because abstract has been fixed.
