### ISSUE TITLE
openapi/ui does not show the APIs

### ISSUE THREAD

**Issue by FintanMcElroy** [OpenLiberty/guide-bean-validation#37]
I am using Eclipse Photon with workspace server OL 18.0.0.3. With the server.xml configured to match that from the sample and pointing at localhost:9080/openapi/ui it does not show any APIs but just the message "No operations defined in spec!". I can execute against the /validatespacecraft using Postman so the API is working OK, it just does not get properly registered / discovered in the openapi UI.

**Comment by yeekangc** [comment]
Thank you for the feedback, @FintanMcElroy.  We are looking into it.

**Comment by gkwan-ibm** [comment]
@FintanMcElroy Would you mind to zip your server directory (e.g. wlp/usr/servers/defaultServer) and send it to us?

**Comment by gkwan-ibm** [comment]
hi @FintanMcElroy, I am going to close this issue. If you still have this problem, you may reopen this issue or open an new issue. Thank you to report this to us.
