### ISSUE TITLE
Add step to add the <feature>beanValidation-2.0</feature> to server.xml

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/guide-bean-validation#86]
The bean validation won't work without the feature so I think we should tell the developer to enable the feature during the guide or any of the other features that might include this feature in it.

**Comment by gkwan-ibm** [comment]
create a section to enable the beanValidation-2.0 by replacing the server.xml

**Comment by gkwan-ibm** [comment]
close
- this issue was addressed

**Comment by steven1046** [comment]
Hi @gkwan-ibm, the guide hotspot at https://openliberty.io/guides/bean-validation.html#enabling-the-bean-validation-feature says beanValidation-2.0 but in the code it is beanValidation-3.0.

**Comment by gkwan-ibm** [comment]
close
-  the above issue was addressed
